include ../makefile.inc

PROJECT=WOLF
PROJECTTYPE=DEMO
OPTLEVEL=2

PRJSRC=$(wildcard src/*.c) $(wildcard src/*.s) $(wildcard src/*.h)

PRJOBJ=src/objs.o \
	src/misc.o \
	src/id_ca.o \
	src/id_vh.o \
	src/id_us.o \
	src/wl_act1.o \
	src/wl_act2.o \
	src/wl_act3.o \
	src/wl_agent.o \
	src/wl_game.o \
	src/wl_inter.o \
	src/wl_menu.o \
	src/wl_play.o \
	src/wl_state.o \
	src/wl_text.o \
	src/wl_main.o \
	src/wl_debug.o \
	src/vi_comm.o \
	src/wl_draw.o \
	src/vi_paws.o \
	src/sd_null.o

include ../makefile-paws.inc

