include ../makefile.inc

PROJECT=QUAKE
PROJECTTYPE=DEMO
PRJSRC=$(wildcard WinQuake/*.c) $(wildcard WinQuake/*.cpp) $(wildcard WinQuake/*.s) $(wildcard WinQuake/*.h)
PRJOBJ=\
	WinQuake/chase.o \
	WinQuake/cl_demo.o \
	WinQuake/cl_input.o \
	WinQuake/cl_main.o \
	WinQuake/cl_parse.o \
	WinQuake/cl_tent.o \
	WinQuake/cmd.o \
	WinQuake/common.o \
	WinQuake/console.o \
	WinQuake/crc.o \
	WinQuake/cvar.o \
	WinQuake/draw.o \
	WinQuake/d_edge.o \
	WinQuake/d_fill.o \
	WinQuake/d_init.o \
	WinQuake/d_modech.o \
	WinQuake/d_part.o \
	WinQuake/d_polyse.o \
	WinQuake/d_scan.o \
	WinQuake/d_sky.o \
	WinQuake/d_sprite.o \
	WinQuake/d_surf.o \
	WinQuake/d_vars.o \
	WinQuake/d_zpoint.o \
	WinQuake/host.o \
	WinQuake/host_cmd.o \
	WinQuake/keys.o \
	WinQuake/menu.o \
	WinQuake/mathlib.o \
	WinQuake/model.o \
	WinQuake/nonintel.o \
	WinQuake/pr_cmds.o \
	WinQuake/pr_edict.o \
	WinQuake/pr_exec.o \
	WinQuake/r_aclip.o \
	WinQuake/r_alias.o \
	WinQuake/r_bsp.o \
	WinQuake/r_light.o \
	WinQuake/r_draw.o \
	WinQuake/r_efrag.o \
	WinQuake/r_edge.o \
	WinQuake/r_misc.o \
	WinQuake/r_main.o \
	WinQuake/r_sky.o \
	WinQuake/r_sprite.o \
	WinQuake/r_surf.o \
	WinQuake/r_part.o \
	WinQuake/r_vars.o \
	WinQuake/screen.o \
	WinQuake/sbar.o \
	WinQuake/sv_main.o \
	WinQuake/sv_phys.o \
	WinQuake/sv_move.o \
	WinQuake/sv_user.o \
	WinQuake/zone.o \
	WinQuake/view.o \
	WinQuake/wad.o \
	WinQuake/world.o \
	WinQuake/cd_null.o \
	WinQuake/net_loop.o \
	WinQuake/net_main.o \
	WinQuake/net_vcr.o \
	WinQuake/in_null.o \
	WinQuake/net_none.o \
	WinQuake/snd_null.o \
	WinQuake/sys_mc1.o \
	WinQuake/vid_mc1.o

include ../makefile-paws.inc
