CFLAGSEXTRA=
include ../makefile.inc

PROJECT=PBSPRITE
PROJECTTYPE=TEST
PRJSRC=$(wildcard *.c) $(wildcard *.cpp) $(wildcard *.s) $(wildcard *.h)
PRJOBJ=pixelblock_sprites.o

include ../makefile-paws.inc
