CFLAGSEXTRA=
include ../makefile.inc

PROJECT=CBZONE
PROJECTTYPE=GAMES
PRJSRC=$(wildcard *.c) $(wildcard *.cpp) $(wildcard *.s) $(wildcard *.h)
PRJOBJ=c_draw.o c_explode.o c_gpr.o c_graphics.o c_main.o c_move.o c_parseopts.o c_scores.o

include ../makefile-paws.inc
