include ../makefile.inc

PROJECT=WOLF3D
PROJECTTYPE=DEMO
PRJSRC=$(wildcard *.c) $(wildcard *.cpp) $(wildcard *.s) $(wildcard *.h)
PRJOBJ=\
	fmopl.o \
	id_ca.o \
	id_in.o \
	id_pm.o \
	id_sd.o \
	id_us_1.o \
	id_vh.o \
	id_vl.o \
	signon.o \
	wl_act1.o \
	wl_act2.o \
	wl_agent.o \
	wl_draw.o \
	wl_game.o \
	wl_inter.o \
	wl_main.o \
	wl_menu.o \
	wl_play.o \
	wl_state.o \
	wl_text.o \
	crt.o

include ../makefile-paws.inc
