CFLAGSEXTRA=
include ../makefile-lto.inc

PROJECT=CHIP-8
PROJECTTYPE=COMPUTER/CHIP-8
PRJSRC=$(wildcard *.c) $(wildcard *.cpp) $(wildcard *.s) $(wildcard *.h)
PRJOBJ=ui.o cpu.o

include ../makefile-paws.inc
