include ../makefile-lto.inc

PROJECT=JFORTH
PROJECTTYPE=COMPUTER/JFORTH
PRJSRC=$(wildcard *.c) $(wildcard *.cpp) $(wildcard *.s) $(wildcard *.h)
PRJOBJ=main.o libforth.o unit.o

include ../makefile-paws.inc
